language: en
pipeline:
- name: WhitespaceTokenizer
- case_sensitive: false
  name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- alias: cvf-word
  name: CountVectorsFeaturizer
- alias: cvf-char
  analyzer: char_wb
  max_ngram: 4
  min_ngram: 1
  name: CountVectorsFeaturizer
- from_pt: true
  model_name: bert
  model_weights: google/bert_uncased_L-4_H-512_A-8
  name: kairon.nlu.featurizer.LanguageModelFeaturizer
- epochs: 180
  name: DIETClassifier
- name: FallbackClassifier
  threshold: 0.75
- name: EntitySynonymMapper
- epochs: 100
  name: ResponseSelector
policies:
- name: MemoizationPolicy
  max_history: 10
- epochs: 100
  name: TEDPolicy
  max_history: 10
- core_fallback_action_name: action_default_fallback
  core_fallback_threshold: 0.5
  enable_fallback_prediction: false
  max_history: 10
  name: RulePolicy
